# Generated by Django 5.2.8 on 2025-11-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Sala/Laboratório')),
                ('capacity', models.IntegerField(verbose_name='Capacidade Máxima de Pessoas')),
                ('type', models.CharField(choices=[('LAB', 'Laboratório'), ('Sala', 'Sala de Aula'), ('AUD', 'Auditório')], default='SALA', max_length=50, verbose_name='Tipo de Recurso')),
                ('active', models.BooleanField(default=True, verbose_name='Disponível para Agendamento')),
            ],
            options={
                'verbose_name': 'Sala Agendável',
                'verbose_name_plural': 'Salas Agendáveis',
            },
        ),
    ]
