# Generated by Django 5.2.8 on 2025-11-19 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Reserva')),
                ('start', models.TimeField(verbose_name='Horário de Início')),
                ('end', models.TimeField(verbose_name='Horário de Fim')),
                ('justification', models.TextField(blank=True, null=True, verbose_name='Motivo/Justificativa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['date', 'start'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Sala/Laboratório')),
                ('capacity', models.IntegerField(verbose_name='Capacidade Máxima de Pessoas')),
                ('type', models.CharField(choices=[('LAB', 'Laboratório'), ('SALA', 'Sala de Aula'), ('AUD', 'Auditório')], default='SALA', max_length=50, verbose_name='Tipo de Recurso')),
                ('active', models.BooleanField(default=True, verbose_name='Disponível para Agendamento')),
            ],
            options={
                'verbose_name': 'Sala Agendável',
                'verbose_name_plural': 'Salas Agendáveis',
            },
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='reservas.room', verbose_name='Sala Reservada'),
        ),
    ]
