# Generated by Django 5.2.8 on 2025-11-19 13:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_agendamento_room_delete_sala_agendamento_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agendamento',
            new_name='Scheduling',
        ),
    ]
