# Generated by Django 5.2.8 on 2025-11-22 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_rename_agendamento_scheduling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Reserva')),
                ('start', models.TimeField(verbose_name='Horário de Início')),
                ('end', models.TimeField(verbose_name='Horário de Fim')),
                ('justification', models.TextField(blank=True, null=True, verbose_name='Motivo/Justificativa')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='reservas.room', verbose_name='Sala Reservada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['date', 'start'],
            },
        ),
        migrations.DeleteModel(
            name='Scheduling',
        ),
    ]
