# Generated by Django 5.2.8 on 2025-11-26 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reservation_delete_scheduling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservas.room', verbose_name='Sala Reservada'),
        ),
    ]
